### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by Hobby-Dev-0** [TeamFussion/Dark_Fussion#3]
Kangers Be alert DMCA Soon

**Comment by LEGEND-OS** [comment]
@Hobby-Dev-0 or by the way ye import repositories kiya h😆😆😆 complaint karo keinshein ko

or ye bol rha tha mereko dm i am friend of keinshein 😅😅😅 plz help me

**Comment by Hobby-Dev-0** [comment]
@LEGEND-OS Yaar Tumhe Toh Bola Nahi Bro Main Toh Isko Bola Tum Mere Friend ho tum bolo toh LEGEND BOT Written on scratch Banadu Usme Kya Hai

**Comment by Hobby-Dev-0** [comment]
> @Hobby-Dev-0 or by the way ye import repositories kiya h😆😆😆 complaint karo keinshein ko
> 
> or ye bol rha tha mereko dm i am friend of keinshein 😅😅😅 plz help me

Mujhe Kisi se bat karne ki nahi jarurat hai bas Copyright dena hai repo khatam
